### ISSUE TITLE
Why use wsol instead of Sol especially since the bot seems to be looking for raydium liquidity then Jupiter

### ISSUE THREAD

**Issue by DemetriusReynolds251** [spaceboundbot/solana-sniper-bot#4]
![image](https://github.com/spaceboundbot/solana-sniper-bot/assets/121074640/d3feccc7-be3c-43f7-89ee-6fae06d88a01)

**Comment by solcasey** [comment]
sol converts to wsol when you snipe
to speed up this process we convert sol in advance
