### ISSUE TITLE
RPC_ENDPOINT is not set

### ISSUE THREAD

**Issue by VespertineD2K** [spaceboundbot/solana-sniper-bot#7]
Hello,

The script keeps telling me that RPC_ENDPOINT is not set, I have it configured like;

RPC_ENDPOINT=https://mainnet.helius-rpc.com/?api-key=MY-API-KEY
RPC_WEBSOCKET_ENDPOINT=wss://mainnet.helius-rpc.com/?api-key=MY-API-KEY 

Is there something I'm somehow inputting wrong?

**Comment by solcasey** [comment]
try another rpc https://shyft.to/
